### PR TITLE
Issue# 3 Resolved

### PR DESCRIPTION
**Pull request by rt-001**

### CODE REVIEW

**Comment by chandel-aman** [comment]
Attach a video showing the normal functioning of the website after your changes

**Comment by rt-001** [comment]
Issue# 3.mov

**Comment by rt-001** [comment]
Uploading Issue# 3.mov…

**Comment by rt-001** [comment]
Uploading Issue# 3.mov…

**Comment by rt-001** [comment]
Uploading Issue# 3 2.mov…

**Comment by rt-001** [comment]
https://user-images.githubusercontent.com/76102333/216568932-a5caef3a-db88-4e36-a1e0-e0d50d35956a.mov

**Comment by rt-001** [comment]
@chandel-aman can u tell me how should I avoid conflicts? ( I did git pull before committing my code )

**Pull request merged**
